language: php

php:
  7.4.7

git:
  depth: 3

branches:
  only:
  -master  

install:
  composer install

  before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS laravelTesting; USE laravelTesting';

